### ISSUE TITLE
Map Support

### ISSUE THREAD

**Issue by Xenovant** [TwnKey/IT3Dumper#1]
First of all, thanks a lot for your hard work, really.

Your dumper works great with characters but I have noticed it doesn't dump map models and I'd like to know if you are planning to add support for them, since my primary interest is to someday be able to fix and improve a lot of them. I know I'd also need a way of reimporting them, but one step at a time.

EDIT: This is in example https://i.imgur.com/ipGkuJo.jpg

**Comment by TwnKey** [comment]
Unfortunately I do not plan to work on maps. I'm expecting a lot of difficulties regarding collisions and special geometries and I don't have the time and motivation to work on it right now. But you can try to reach out to Armada (https://github.com/eArmada8) who previously worked on Ys 8 models among other stuff, and did some work on maps for the cold steel games actually.

**Comment by Xenovant** [comment]
Thanks, I'll take a loot at his work.
